# Generated by Django 5.2.5 on 2025-09-07 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='email',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
    ]
