# Generated by Django 5.2.5 on 2025-09-05 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='level',
            field=models.CharField(choices=[('LOW', 'low'), ('MID', 'mid'), ('HIGH', 'high')], default='low', max_length=10),
        ),
    ]
