# Generated by Django 5.2.5 on 2025-09-05 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivos', '0002_alert_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='level',
            field=models.CharField(choices=[('CRITICAL', 'critical'), ('MID', 'mid'), ('HIGH', 'high')], default='mid', max_length=10),
        ),
    ]
